$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$requirementsPath = Join-Path $repoRoot "apps\browser-worker\requirements.txt"
$lockPath = Join-Path $repoRoot "apps\browser-worker\requirements.lock.txt"
$tempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("jobot-python-lock-" + [Guid]::NewGuid().ToString("N"))
$lockTempPath = $null
$lockBackupPath = $null
$cleanupFailed = $false

function Invoke-Checked {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Operation,
        [Parameter(Mandatory = $true)]
        [string]$FilePath,
        [Parameter(Mandatory = $false)]
        [string[]]$ArgumentList = @()
    )

    & $FilePath @ArgumentList
    if ($LASTEXITCODE -ne 0) {
        throw "$Operation failed with exit code $LASTEXITCODE."
    }
}

try {
    if (-not (Test-Path -LiteralPath $requirementsPath -PathType Leaf)) {
        throw "Requirements source apps/browser-worker/requirements.txt was not found."
    }
    try {
        Get-Command py -ErrorAction Stop | Out-Null
    }
    catch {
        throw "Python launcher 'py' was not found."
    }

    try {
        New-Item -ItemType Directory -Path $tempRoot -Force -ErrorAction Stop | Out-Null
    }
    catch {
        throw "Creating the temporary Python environment failed."
    }
    $venvPath = Join-Path $tempRoot "venv"
    Invoke-Checked -Operation "Creating the temporary Python environment" -FilePath "py" -ArgumentList @("-3.12", "-m", "venv", $venvPath)

    $venvPython = Join-Path $venvPath "Scripts\python.exe"
    if (-not (Test-Path -LiteralPath $venvPython -PathType Leaf)) {
        throw "The temporary Python environment did not initialize."
    }

    $browserWorkerPath = Join-Path $repoRoot "apps\browser-worker"
    Push-Location -LiteralPath $browserWorkerPath
    try {
        Invoke-Checked -Operation "Resolving Python requirements" -FilePath $venvPython -ArgumentList @(
            "-m", "pip", "install", "--disable-pip-version-check", "--no-cache-dir", "-r", "requirements.txt"
        )

        $freezeLines = @(& $venvPython -m pip freeze --disable-pip-version-check)
        $freezeExitCode = $LASTEXITCODE
    }
    finally {
        Pop-Location
    }
    if ($freezeExitCode -ne 0) {
        throw "Collecting resolved Python packages failed with exit code $freezeExitCode."
    }
    $packages = @(
        $freezeLines |
            Where-Object { -not [String]::IsNullOrWhiteSpace($_) } |
            Sort-Object -CaseSensitive:$false
    )
    if ($packages.Count -eq 0) {
        throw "pip freeze returned no packages; refusing to replace the Python lock."
    }

    $header = @(
        "# Generated from apps/browser-worker/requirements.txt by scripts/dev/refresh-python-lock.ps1.",
        "# Source spec is the single source of truth; regenerate with npm run browser:lock.",
        "# Do not edit this file manually."
    )
    $content = ($header + $packages) -join [Environment]::NewLine
    $content += [Environment]::NewLine
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    $lockDirectory = Split-Path -Parent $lockPath
    $lockTempPath = Join-Path $lockDirectory (".requirements.lock-" + [Guid]::NewGuid().ToString("N") + ".tmp")
    $lockBackupPath = Join-Path $lockDirectory (".requirements.lock-backup-" + [Guid]::NewGuid().ToString("N") + ".tmp")
    try {
        [System.IO.File]::WriteAllText($lockTempPath, $content, $utf8NoBom)
    }
    catch {
        throw "Writing the temporary Python lock failed."
    }
    try {
        if (Test-Path -LiteralPath $lockPath -PathType Leaf) {
            [System.IO.File]::Replace($lockTempPath, $lockPath, $lockBackupPath)
            $lockTempPath = $null
            Remove-Item -LiteralPath $lockBackupPath -Force -ErrorAction Stop
            $lockBackupPath = $null
        }
        else {
            [System.IO.File]::Move($lockTempPath, $lockPath)
            $lockTempPath = $null
        }
    }
    catch {
        throw "Atomically replacing the Python lock failed."
    }
    Write-Host ("Wrote {0} pinned packages to apps/browser-worker/requirements.lock.txt" -f $packages.Count)
}
finally {
    try {
        if ($lockTempPath -and (Test-Path -LiteralPath $lockTempPath -PathType Leaf)) {
            Remove-Item -LiteralPath $lockTempPath -Force -ErrorAction Stop
        }
    }
    catch {
        $cleanupFailed = $true
    }
    try {
        if ($lockBackupPath -and (Test-Path -LiteralPath $lockBackupPath -PathType Leaf)) {
            Remove-Item -LiteralPath $lockBackupPath -Force -ErrorAction Stop
        }
    }
    catch {
        $cleanupFailed = $true
    }
    try {
        if ($tempRoot -and (Test-Path -LiteralPath $tempRoot -PathType Container)) {
            Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction Stop
        }
    }
    catch {
        $cleanupFailed = $true
    }
    if ($cleanupFailed) {
        throw "Temporary lock cleanup failed."
    }
}
